### ISSUE TITLE
Сборка icons для android

### ISSUE THREAD

**Issue by Yakutoc** [salute-developers/plasma#1129]
Задача: Автоматизировать сборку иконок для адроид

## Dispatches custom event

В репозитории `plasma` cоздаем `workflow` который создает `custom event`:

```yml
name: Dispatches custom event

on:
    workflow_dispatch:
    # Запускаем когда у нас закончился publish latest
    workflow_run:
        workflows: [ "Release" ]
        branches: [ master ]
        types:
            - completed

jobs:
    trigger:
        runs-on: ubuntu-latest

        steps:
            # Добавим еще один шаг чтобы убедиться был ли в релизе пакет - `plasma-icons`  
            - name: Trigger Workflow
              run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/{REPO}/{REPO}/dispatches \
                -d '{"event_type":"plasma-released","client_payload":{"released":"true"}}'
```

#### Примечание: 

**REPO** заменяем на целевой репозиторий в котором хотим запустить событие. 

В нашем случае это репозиторий с андроид разработкой.    

## Subscribe

В репозитории c android разработкой cоздаем `workflow` который подписан на наш `custom event`:

```yml
name: Subscribe to custom event

on:
  repository_dispatch:
    types: [build-icons]

jobs:
  plasma-icons:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.android-icons.outputs.artifact-url }}
    steps:
      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: salute-developers/plasma
          ref: ${{ github.event.client_payload.ref || 'master' }}
          show-progress: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Bootstrap web project
        run: npm ci

      - name: Generate android icons
        run: |
          npx lerna bootstrap --ignore-scripts --scope="@salutejs/plasma-icons" 
          npm run generate:android --prefix="packages/plasma-icons"

      - name: Save android icons
        id: android-icons
        uses: actions/upload-artifact@v4.1.0
        with:
          name: android-icons-${{ github.event.client_payload.version }}.zip
          path: packages/plasma-icons/archives/android-icons.zip

  download:
    needs: [plasma-icons]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Download android icons
        run: |
          curl -o plasma-icons ${{ needs.plasma-icons.outputs.url }}

      # И тут уже делаем что хотим с этим архивом  
```

в этом workflow будет:
- сборка plasma-icons из репозитория `plasma` (занимает где-то 2-3 мин)
- логика сборки уже через Gradle
