### ISSUE TITLE
Handling external pull request by fork

### ISSUE THREAD

**Issue by Yakutoc** [salute-developers/plasma#805]
TD;LR

Использование события `pull_request_target` без должных мер предосторожности может повлечь за собой раскрытие всех секретов неавторизованным пользователям GitHub. 

[DOCs pull_request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)

GITHUB_SHA 
> Last merge commit on the GITHUB_REF branch

GITHUB_REF
> PR merge branch refs/pull/:prNumber/merge

[DOCs pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)

GITHUB_SHA
> Last commit on the PR base branch

GITHUB_REF
> PR base branch

Из-за этой разницы в том на что/куда смотрит target события, в шаге с `checkout` нужно будет **явно** **указать** `ref`

```yml
- name: Checkout
  uses: actions/checkout@v4
  with:
    show-progress: false
    fetch-depth: 0
    ref: refs/pull/${{github.event.pull_request.number}}/merge
```
 
И как раз это является потенциальным вектором атаки. 

В статье [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) подробно об этом рассказывается. 

> TL;DR: Combining pull_request_target workflow trigger with an explicit checkout of an untrusted PR is a dangerous practice that may lead to repository compromise.

### Изменить подход к организации наших workflow  

Полностью меняем подход к тому как мы обрабатываем внешний PR's через fork. 

**Исключаем** workflow для таких PR где так или иначе фигурируют secrets, типа `github_token`. 

Например "Publish Canary" и deploy документации с песочницей.

### Использование "Еnvironment" для получение approve

Добавляем ограничение на запуск для `environment === 'external'`.

Переделанная конфигурация для "Publish Canary".

```yml
name: Publish Canary

on:
  pull_request_target:
    branches:
      - dev

jobs:
  authorize:
    runs-on: ubuntu-latest

    ## github.event_name == 'pull_request_target' - защита от дурака
    ## github.event.pull_request.head.repo.full_name != github.repository - убеждаемся что PR сделан через fork
    ## Если да используем environment: external и тогда нужен approve от члена команды для запуска этого workflow
     
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}

    steps:
      - name: Echo
        run: |
          echo "External pull request approved by code owners"

  publish:
    name: Canary version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    with:
      ref: refs/pull/${{github.event.pull_request.number}}/merge
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
```

Внешний pull request **не запустит** ни один workflow в котором будут подобные ограничения. 

Членам команды будут отправлены уведомления о том что нужно поставить approve на запуск workflow. 

И тем самым исключаем запуск в целевом репозитории **untrusted** code.        
 
<img width="1272" alt="Screenshot 2023-10-10 at 16 44 08" src="https://github.com/salute-developers/plasma/assets/2895992/48dd24f9-9512-43d3-87b0-ad7ba283bb16">

**Comment by Yakutoc** [comment]
### Publish RC 

Для этого workflow событие `pull_request_target` не походит. 

После закрытия PR и запуска `auto shipit` считает что до сих пор находится в ветке PR и запускает публикацию canary версии. 

Поэтом предлагаю перейти на `on: push`. 

В нашем случае после того как прошли обязательные проверки в merge-queue, происходит push в dev. С учетом этого и сделана новая конфигурация. 

```yml
name: Publish RC

on:
  push:
    branches:
      - dev

jobs:
  publish:
    name: Publish RC version

    ## Push от друго actor не запустит этот workflow
    if: ${{ github.actor == 'github-merge-queue[bot]' }}

    uses: ./.github/workflows/publish-common.yml
    with:
      with-update-package-lock: true
      commit-message: "chore: update package-locks"
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
```

**Comment by Yakutoc** [comment]
### Какие workflows нужно будет адаптировать

- Publish canary
- Publish RC
- PR theme-builder
- Component Performance Testing (PR)
-  PR Documentation and Storybook

Все эти workflows имеют запись 

```yml
on:
  pull_request:
    branches:
      - dev
      - master
```   

И для master нужно будет оставить как раз `on: pull_request`.
