### ISSUE TITLE
Retry failure step

### ISSUE THREAD

**Issue by Yakutoc** [salute-developers/plasma#884]
# Задача 

Сделать retry для упавшего **шага**

## Зачем

У нас есть такой шаг отвечающий за обновление версий в `package-lock.json` файлах. 

```yml
- name: Update package-lock files
  if: ${{ inputs.with-update-package-lock }}
  uses: ./.github/actions/update-package-lock
  with:
    commit-message: ${{ inputs.commit-message }}
    token: ${{ secrets.gh_token }}
```  

Иногда бывает, что во время релиза может упасть с ошибкой которую мы **пока что** не знаем как купировать 

```bash
npm ERR! code ECONNRESET

npm ERR! errno ECONNRESET

npm ERR! network Invalid response body while trying to fetch [https://registry.npmjs.org/@salutejs%2fplasma-sb-utils:](https://registry.npmjs.org/@salutejs%2fplasma-sb-utils:) aborted

npm ERR! network This is a problem related to network connectivity.

npm ERR! network In most cases you are behind a proxy or have bad network settings.

npm ERR! network

npm ERR! network If you are behind a proxy, please make sure that the

npm ERR! network 'proxy' config is set properly. See: 'npm help config'

npm ERR! A complete log of this run can be found in: /home/runner/.npm/\_logs/2023-11-30T04\_00\_21\_052Z-debug-0.log
``` 

Локальный запуск этой же команду отработает корректно. 

### Решение 

Так как ошибка явно не в нашей инфре, можем попробовать запустить команду еще раз 
  
Есть такой github action - https://github.com/nick-fields/retry

Как пример того что мы может сделать на своей стороне 

```yml
- name: Update package-lock files
   uses: nick-fields/retry@master
   with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 60
          command: |
            npm i ${{ env.options }}
            lerna clean -y
            lerna exec --no-private -- npm i ${{ env.options }} --ignore-scripts
            npm i ${{ env.options }}
```

Можно почитать - https://www.thisdot.co/blog/how-to-retry-failed-steps-in-github-action-workflows
